### ISSUE TITLE
Delete artifact api request sometimes fails - add retry?

### ISSUE THREAD

**Issue by pankajbokdia** [christian-korneck/delete-run-artifacts-action#6]
I am getting this error when using this 

Run christian-korneck/delete-run-artifacts-action@v1
  with:
    parent_runid: 261405865
    parent_repo: pankajbokdia/repoName
  env:
    GITHUB_TOKEN: ***
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
artifacts before deletion: 1
processing artifact: build 18063905
status: 204
artifacts after deletion: 1
##[error]🛑 not all artifacts deleted (1 remaining)

Please help

**Comment by christian-korneck** [comment]
hi @pankajbokdia , thanks for reaching out.
Unfortunately I can't reproduce your problem. I just created a test repo with a minimal github workflow that creates two artifacts and then triggers this action to delete them. The deletion just worked fine.

Here's the test repo (feel free to use it as a reference):
https://github.com/christian-korneck/test322

That's from the log of the workflow run:

```
Run christian-korneck/delete-run-artifacts-action@v1
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
artifacts before deletion: 2
processing artifact: test1 18080653
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
status: 204
processing artifact: test2 18080654
status: 204
artifacts after deletion: 0
🎉 all artifacts deleted
```

Is your repo available publicly somewhere? Or could you share the relevant parts of the workflow? Thanks.

**Comment by joeleduardo** [comment]
i got the same error but looks is randomly if i re-run the action works!!

**Comment by christian-korneck** [comment]
Thanks @joeleduardo for the comment. Sounds a bit like a github reliability issue. However, I've never seen it and also couldn't reproduce it even with a high number of test runs. How often do you see this happen? (I could imagine that these are rare partial server side outages of certain github services?). Is there anything special about the way you handle artifacts in your workflow (i.e. very large artifacts, etc)?

(If someone would point me to a public repo with a failed run I could contact github support?)

**Comment by Asamsig** [comment]
We also get this error intermittently, but artifacts are always deleted, to us it seems like a cache issue or similar, simply that Github reports artifacts that have actually been deleted.
We could be interested in adding a retry option, if you're open for that.

**Comment by christian-korneck** [comment]
ok, judging from the number of reports in this issue this seems to happen more often than I expected.

> We could be interested in adding a retry option, if you're open for that.

sounds like a good idea. Feel free to send a PR, if you like.

**Comment by christian-korneck** [comment]
I've now [added](https://github.com/christian-korneck/delete-run-artifacts-action/commit/4cee595c600e0de644ff62977577be4b4f8811ed) this backoff retry behaviour:

- when no artifacts are found, retry for up to ~ 4 minutes
- when we end up with undeleted artifacts, retry for up to ~ 20 minutes

I hope this solves your problems @Asamsig @joeleduardo @pankajbokdia . If not, let me know. Thanks a lot for your feedback!
