### ISSUE TITLE
How to delete all artifact periodically?

### ISSUE THREAD

**Issue by natheeshsunway** [christian-korneck/delete-run-artifacts-action#8]
like corn job 
`on:
  schedule:
    - cron: '20 3 * * 2' 
`

We need parent id for deleting particular artifacts.Is it a way to delete all artefacts :) ?

**Comment by christian-korneck** [comment]
That's out of scope for _this_ github action. But there are other actions for that purpose: https://github.com/marketplace/actions/purge-artifacts

**Comment by natheeshsunway** [comment]
Sure...
